---
version: "2.1"
services:
  minio:
    image: quay.io/minio/minio:latest
    container_name: minio
    command: ["server", "/data", "--console-address", ":9090"]
    user: 0:0
    environment:
      - MINIO_ROOT_USER=user
      - MINIO_ROOT_PASSWORD=password
      - TZ=Asia/Shanghai
      - MINIO_SERVER_URL=https://example.com
      - MINIO_BROWSER_REDIRECT_URL=https://c.example.com
    volumes:
      - /mnt/heimusic/minio:/data
    ports:
      - "127.0.0.1:9000:9000"
      - "127.0.0.1:9090:9090"
    restart: unless-stopped
    #network_mode: "host"
