server:
  port: 80

spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/heimusic?serverTimezone=UTC
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: example_username
      password: example_password
  redis:
    host: localhost
    port: 6379
  mail:
    host: smtp.example.com
    port: 465
    username: example@example.com
    password: example_password
    protocol: smtp
    properties:
      mail:
        smtp:
          ssl:
            enable: true


mybatis-plus:
  #  global-config:
  #    db-config:
  #      table-prefix: tb_
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    root: info

heimusic:
  domain: example.com
  minio:
    endpoint: https://example.com
    accessKey: example
    secretKey: example
  redis:
    url: redis://127.0.0.1:6379